local Translations = {

    client = {
        lang_1 = 'Equipment Menu',
        lang_2 = 'Gold Rush Menu',
        lang_3 = 'Equipment Info',
        lang_4 = 'Add Paydirt',
        lang_5 = 'Add Water',
        lang_6 = 'Collect Gold',
        lang_7 = 'Repair Equipment ($',
        lang_8 = ')',
        lang_9 = 'Packup Equipment',
        lang_10 = 'Gold Equipment Menu',
        lang_11 = 'Equipment ID: ',
        lang_12 = 'Owner: ',
        lang_13 = ' (',
        lang_14 = ')',
        lang_15 = 'Condition: ',
        lang_16 = ' (Repair Cost $',
        lang_17 = ')',
        lang_18 = 'Water: ',
        lang_19 = 'Paydirt: ',
        lang_20 = 'Small Nugget: ',
        lang_21 = 'Medium Nugget: ',
        lang_22 = 'Large Nugget: ',
        lang_23 = 'Repairing your Gold Rocker..',
        lang_24 = 'Not Enough Cash!',
        lang_25 = 'Paydirt Full',
        lang_26 = 'Adding Paydirt..',
        lang_27 = 'Paydirt Needed!',
        lang_28 = 'Water Full',
        lang_29 = 'Adding Water..',
        lang_30 = 'Water Needed!',
        lang_31 = 'Collecting Gold..',
        lang_32 = 'Needs Repaired!',
        lang_33 = 'Packing Up & Collecting Gold..',
        lang_34 = 'Can\'t Place Here!',
        lang_35 = 'Maximum Equipment!',
        lang_36 = 'You are currently busy!',
        lang_37 = 'Can\'t do that here!',
        lang_38 = 'Collecting Paydirt..',
        lang_39 = 'Can\'t do that here!',
        lang_40 = 'Collecting Water..',
        lang_41 = 'Open ',
        lang_42 = 'Gold Agent Menu',
        lang_43 = 'Smelt Gold',
        lang_44 = 'smelt your nuggets into gold bars',
        lang_45 = 'Sell Gold Bars',
        lang_46 = ' per gold bar',
        lang_47 = 'Smelt Gold',
        lang_48 = 'Choose Nugget Type',
        lang_49 = 'Small Nuggets (',
        lang_50 = 'Medium Nuggets (',
        lang_51 = 'Large Nuggets (',
        lang_52 = ' needed)',
        lang_53 = 'Amount',
        lang_54 = 'amount of gold bars you want to produce',
        lang_55 = 'Smelting ',
        lang_56 = ' x Gold Bar',
        lang_57 = 'Not Enough Nuggets',
        lang_58 = 'you don\'t have enough small nuggets to produce that!',
        lang_59 = 'you don\'t have enough medium nuggets to produce that!',
        lang_60 = 'you don\'t have enough large nuggets to produce that!',
        lang_61 = 'Gold Agent Menu',
        lang_62 = 'Sell Gold Bars',
        lang_63 = 'Amount',
        lang_64 = 'current sell price per bar $',
        lang_65 = 'Not Enough Gold Bars',
        lang_66 = 'you are not holding that many gold bars!',
        lang_67 = 'Goldrush Shop',
        lang_68 = 'buy gold equipment',
    },

    server = {
        lang_1 = 'Max Reached',
        lang_2 = 'cronjob ran for rex-goldrush upkeep',
    },

}

Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})

-- Lang:t('client.lang_1')
-- Lang:t('server.lang_1')
