local Translations = {

    client = {
        lang_1 = 'Membership Required',
        lang_2 = 'Manager Menu',
        lang_3 = 'Boss Menu',
        lang_4 = 'manage staff, money and storage',
        lang_5 = 'Make Membership Cards',
        lang_6 = '$',
        lang_7 = ' per card',
        lang_8 = 'Not Authorised!',
        lang_9 = 'Create Memebership Cards',
        lang_10 = 'How Many',
        lang_11 = 'Creating Membership Cards',
        lang_12 = 'Money Needed',
        lang_13 = 'not enough money in your boss account!',
        lang_14 = 'Not Authorised!',
        lang_15 = 'Distribution Menu',
        lang_16 = 'Goods In',
        lang_17 = 'Goods Out',
        lang_18 = 'Add Delivery Stock',
        lang_19 = 'current stock ',
        lang_20 = ' moonshine',
        lang_21 = 'Add Delivery Stock',
        lang_22 = 'How Much',
        lang_23 = 'current stock ',
        lang_24 = ' moonshine',
        lang_25 = 'Not holding that much!',
        lang_26 = 'Not Enough Law!',
        lang_27 = 'not enough law on duty!',
        lang_28 = 'Lemoyne Speakeasy',
        lang_29 = 'Cattail Pond Speakeasy',
        lang_30 = 'New Austin Speakeasy',
        lang_31 = 'Hanover Speakeasy',
        lang_32 = 'Manzanita Post Speakeasy',
        lang_33 = 'Delivery Failed',
        lang_34 = 'you ran out of time',
        lang_35 = 'Time Remaining : ',
        lang_36 = 'Delivery Successful',
        lang_37 = 'Delivery Failed!',
        lang_38 = 'your delivery failed due to damaged wagon!',
        lang_39 = 'Open Menu',
        lang_40 = 'Not Authorised!',
        lang_41 = 'Brewer Menu',
        lang_42 = 'Add Ingredience',
        lang_43 = 'Corn: ',
        lang_44 = 'Sugar: ',
        lang_45 = 'Water: ',
        lang_46 = 'Yeast: ',
        lang_47 = 'Empty Jug: ',
        lang_48 = 'Mash: ',
        lang_49 = 'Moonshine: ',
        lang_50 = 'Collect Product',
        lang_51 = 'Corn',
        lang_52 = 'Sugar',
        lang_53 = 'Water',
        lang_54 = 'Yeast',
        lang_55 = 'Empty Jug',
        lang_56 = 'How Many',
        lang_57 = 'Max Reached!',
        lang_58 = 'Not holding enough corn!',
        lang_59 = 'Not holding enough sugar!',
        lang_60 = 'Not holding enough water!',
        lang_61 = 'Not holding enough yeast!',
        lang_62 = 'Not holding enough empty jugs!',
        lang_63 = 'Collecting Moonshine..',
        lang_64 = 'No moonshine to take',
        lang_65 = 'Employees Only!',
    },

    server = {
        lang_1 = 'speakeasy moonshine job ran',
    },

}

Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})

-- Lang:t('client.lang_1')
-- Lang:t('server.lang_1')
